#Esse código é livre e vivo, se vc tem alguma contribuição será bem-vinda. Criado por Bruno Duarte, caso utilize, credite o autor ;) 
import pyautogui
import pyautogui as abrirSap
import time 


opcao = pyautogui.confirm("Olá, selecione um das variantes e aguarde a execução:", buttons = ['IW38' , 'IW37N'])
abrirSap.PAUSE = 0.5

if opcao == "IW38":
    abrirSap.hotkey('winleft', 'r')
    abrirSap.write('saplogon.exe')
    abrirSap.press('enter')
    time.sleep(1)
    abrirSap.press('down')
    abrirSap.press('down')
    abrirSap.press('down')
    abrirSap.press('down')
    abrirSap.press('down')
    abrirSap.press('down')
    abrirSap.press('enter')
    time.sleep(8)               
    abrirSap.press('esc')
    abrirSap.press('enter')
    time.sleep(1)
    abrirSap.write('iw38')
    abrirSap.press('enter')
    time.sleep(1)
    abrirSap.hotkey('shift','f5')
    time.sleep(3)
    abrirSap.write('SIM_MI_PD')
    abrirSap.hotkey('tab')
    abrirSap.hotkey('tab')
    abrirSap.hotkey('tab')
    abrirSap.hotkey('tab')
    abrirSap.hotkey('delete')
    abrirSap.hotkey('tab')
    abrirSap.hotkey('tab')
    abrirSap.hotkey('tab')
    abrirSap.hotkey('tab')
    abrirSap.hotkey('tab')
    abrirSap.hotkey('tab')
    abrirSap.press('enter')
    time.sleep(2)
    abrirSap.hotkey('tab')
    abrirSap.hotkey('tab')
    abrirSap.press('enter')
    time.sleep(1)
    abrirSap.alert("Seu SAP foi aberto, na transação IW38, insira as ordens e prossiga com a execução")
elif opcao == "IW37N":
    abrirSap.hotkey('winleft', 'r')
    abrirSap.write('saplogon.exe')
    abrirSap.press('enter')
    time.sleep(1)
    abrirSap.press('down')
    abrirSap.press('down')
    abrirSap.press('down')
    abrirSap.press('down')
    abrirSap.press('down')
    abrirSap.press('down')
    abrirSap.press('enter')
    time.sleep(8)               
    abrirSap.press('esc')
    abrirSap.press('enter')
    time.sleep(1)
    abrirSap.write('iw37n')
    abrirSap.press('enter')
    time.sleep(1)
    abrirSap.hotkey('shift','f5')
    time.sleep(3)
    abrirSap.write('SIM_MI_PD')
    abrirSap.hotkey('tab')
    abrirSap.hotkey('tab')
    abrirSap.hotkey('tab')
    abrirSap.hotkey('tab')
    abrirSap.hotkey('delete')
    abrirSap.hotkey('tab')
    abrirSap.hotkey('tab')
    abrirSap.hotkey('tab')
    abrirSap.hotkey('tab')
    abrirSap.hotkey('tab')
    abrirSap.hotkey('tab')
    abrirSap.press('enter')
    time.sleep(2)
    abrirSap.hotkey('tab')
    abrirSap.hotkey('tab')
    abrirSap.hotkey('tab')
    abrirSap.hotkey('tab')
    abrirSap.press('enter')
    time.sleep(1)
    abrirSap.alert("Seu SAP foi aberto, na transação IW37N, insira as ordens e prossiga com a execução")


